# Generated by Django 3.2.13 on 2022-04-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
